import { useState } from 'react'
import {
  formatSignedKg,
  formatTrainingTime,
  formatVolume,
  PROGRESS_PERIODS,
  trendOf,
  useProgressSummary,
  useStatsOverview,
  type ExerciseProgress,
  type MuscleGroupVolume,
  type PersonalRecord,
  type ProgressAssessment,
  type ProgressPeriod,
  type ProgressSummary,
  type RecentWorkout,
  type TrendBucket,
} from '../stats'
import { formatRelativeDay, formatShortDate, formatWeight } from '../workout'

/** What the progress badge reads for each overall verdict. */
const PROGRESS_ASSESSMENT_LABEL: Record<ProgressAssessment, string> = {
  improving: 'Improving',
  stable: 'Stable',
  declining: 'Declining',
  not_enough_data: 'Not enough data',
}

/** The assessment maps onto the same badge tones the workout summary uses. */
const PROGRESS_ASSESSMENT_TONE: Record<ProgressAssessment, string> = {
  improving: 'better',
  stable: 'first',
  declining: 'worse',
  not_enough_data: 'first',
}

/** One number and its label. The building block of every summary below. */
function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="stat-cell">
      <p className="label">{label}</p>
      <p className="stat-value">{value}</p>
    </div>
  )
}

/** An arrow and a signed number. Direction only — no judgement about which way
 *  is good, because the app does not know whether the user is cutting or bulking. */
function Trend({ changeKg }: { changeKg: number }) {
  const trend = trendOf(changeKg)
  const arrow = trend === 'up' ? '▲' : trend === 'down' ? '▼' : '•'
  return (
    <span className="trend" data-trend={trend}>
      <span aria-hidden="true">{arrow}</span> {formatSignedKg(changeKg)} kg
    </span>
  )
}

function PersonalRecordRow({ record }: { record: PersonalRecord }) {
  return (
    <li className="stat-row">
      <div className="stat-row-main">
        <p className="stat-row-title">{record.exerciseName}</p>
        <p className="stat-row-note">
          Best set · {formatRelativeDay(record.achievedAt)}
        </p>
      </div>
      <div className="stat-row-figures">
        <p className="stat-row-value">
          {formatWeight(record.weightKg)} kg × {record.reps}
        </p>
        {/* An estimate off a bodyweight set is just 0, so it is not worth showing. */}
        {record.estimatedOneRepMaxKg > 0 && (
          <p className="stat-row-note">
            ≈{formatWeight(record.estimatedOneRepMaxKg)} kg 1RM
          </p>
        )}
      </div>
    </li>
  )
}

function RecentWorkoutRow({ workout }: { workout: RecentWorkout }) {
  return (
    <li className="stat-row">
      <div className="stat-row-main">
        <p className="stat-row-title">{workout.dayName}</p>
        <p className="stat-row-note">
          {formatShortDate(workout.completedAt)} ·{' '}
          {formatTrainingTime(workout.durationSeconds)} ·{' '}
          {workout.exerciseCount} exercises · {workout.setCount} sets
        </p>
      </div>
      <div className="stat-row-figures">
        <p className="stat-row-value">{formatVolume(workout.volumeKg)}</p>
        {workout.bodyWeightKg !== null && (
          <p className="stat-row-note">
            {formatWeight(workout.bodyWeightKg)} kg bw
          </p>
        )}
      </div>
    </li>
  )
}

/** `+3,120`, `-500`, `0` — the sign carries the meaning of a volume change. */
function signedVolume(kg: number): string {
  const rounded = Math.round(kg)
  return `${rounded >= 0 ? '+' : ''}${rounded.toLocaleString()} kg`
}

function deltaClass(delta: number | null): string {
  if (delta === null || delta === 0) return ''
  return delta > 0 ? 'ai-delta-up' : 'ai-delta-down'
}

/**
 * The AI general-progress summary. Analyses overall training across every
 * workout in the selected window (last week / month / 3 months / all time) — a
 * different question from the post-workout summary, which compares one session
 * to earlier sessions of the same training day. The narrative is generated by
 * OpenAI on the backend; the browser never sees the key.
 */
function ProgressAiSummary() {
  const [period, setPeriod] = useState<ProgressPeriod>('week')
  const { state, regenerate } = useProgressSummary(period)
  const [regenerating, setRegenerating] = useState(false)

  async function handleRegenerate() {
    setRegenerating(true)
    try {
      await regenerate()
    } finally {
      setRegenerating(false)
    }
  }

  return (
    <section className="ai-summary" aria-label="AI progress summary">
      <p className="ai-summary-kicker">AI Progress Summary</p>

      <div className="progress-period" role="tablist" aria-label="Time period">
        {PROGRESS_PERIODS.map((option) => (
          <button
            key={option.value}
            type="button"
            role="tab"
            aria-selected={period === option.value}
            className={`progress-period-tab${
              period === option.value ? ' is-active' : ''
            }`}
            onClick={() => setPeriod(option.value)}
          >
            {option.label}
          </button>
        ))}
      </div>

      {state.status === 'loading' && (
        <p className="history-note">Analyzing progress…</p>
      )}

      {(state.status === 'error' || state.status === 'not-found') && (
        <>
          <p className="error" role="alert">
            {state.status === 'error'
              ? state.message
              : 'Could not generate AI summary. Your workout data is still saved.'}
          </p>
          <button
            type="button"
            className="ai-summary-regenerate"
            disabled={regenerating}
            onClick={() => void handleRegenerate()}
          >
            {regenerating ? 'Analyzing…' : 'Try again'}
          </button>
        </>
      )}

      {state.status === 'ready' && (
        <ProgressSummaryBody
          summary={state.data}
          regenerating={regenerating}
          onRegenerate={() => void handleRegenerate()}
        />
      )}
    </section>
  )
}

/** The rendered progress summary: badge, narrative, chips, and collapsible charts. */
function ProgressSummaryBody({
  summary,
  regenerating,
  onRegenerate,
}: {
  summary: ProgressSummary
  regenerating: boolean
  onRegenerate: () => void
}) {
  const { metrics } = summary
  const hasCharts =
    metrics.volumeTrend.length > 0 ||
    metrics.muscleGroups.length > 0 ||
    metrics.topExercises.length > 0

  return (
    <>
      <span
        className={`ai-badge ai-badge-${PROGRESS_ASSESSMENT_TONE[summary.assessment]}`}
      >
        {PROGRESS_ASSESSMENT_LABEL[summary.assessment]}
      </span>

      <h2 className="ai-summary-headline">{summary.headline}</h2>

      <p className="ai-summary-text">{summary.summary}</p>

      {summary.status === 'unavailable' && (
        <p className="ai-summary-note">
          The AI coach note is unavailable right now — the numbers below are
          still your real results.
        </p>
      )}

      {/* Headline metrics for the window: workouts, volume, sets, per week. */}
      <div className="progress-stat-row">
        <div className="progress-stat">
          <p className="label">Workouts</p>
          <p className="progress-stat-value">{metrics.workouts}</p>
        </div>
        <div className="progress-stat">
          <p className="label">Volume</p>
          <p className="progress-stat-value">
            {formatVolume(metrics.totalVolume)}
          </p>
        </div>
        <div className="progress-stat">
          <p className="label">Sets</p>
          <p className="progress-stat-value">{metrics.totalSets}</p>
        </div>
        <div className="progress-stat">
          <p className="label">Per week</p>
          <p className="progress-stat-value">
            {metrics.averageWorkoutsPerWeek}
          </p>
        </div>
      </div>

      {metrics.previous && (
        <VolumeVsPrevious current={metrics.totalVolume} previous={metrics.previous.volume} />
      )}

      {summary.consistencyNote && (
        <p className="ai-summary-trend-note">{summary.consistencyNote}</p>
      )}

      {summary.highlights.length > 0 && (
        <SummaryChips heading="Highlights" items={summary.highlights} tone="up" />
      )}
      {summary.weakSpots.length > 0 && (
        <SummaryChips heading="Watch" items={summary.weakSpots} tone="down" />
      )}

      {summary.comparisonNote && (
        <p className="ai-summary-effort-note">{summary.comparisonNote}</p>
      )}

      {summary.recommendations.length > 0 && (
        <div className="ai-recommendation">
          <span className="ai-recommendation-label">Recommendations</span>
          <ul className="ai-summary-notes">
            {summary.recommendations.map((rec, index) => (
              <li key={index}>{rec}</li>
            ))}
          </ul>
        </div>
      )}

      {/* The charts are heavier, so tuck them into a collapsible details block
          to keep the summary compact on a phone. */}
      {hasCharts && (
        <details className="progress-charts">
          <summary className="progress-charts-summary">
            View charts &amp; details
          </summary>
          <div className="progress-charts-body">
            {metrics.volumeTrend.length > 0 && (
              <VolumeTrendChart trend={metrics.volumeTrend} />
            )}
            {metrics.muscleGroups.length > 0 && (
              <MuscleGroupChart groups={metrics.muscleGroups} />
            )}
            {metrics.topExercises.length > 0 && (
              <TopExerciseTable exercises={metrics.topExercises} />
            )}
            {metrics.bestSets.length > 0 && (
              <ul className="stat-list">
                <li className="ai-summary-subhead">Best sets</li>
                {metrics.bestSets.map((set) => (
                  <li className="stat-row" key={set.name}>
                    <div className="stat-row-main">
                      <p className="stat-row-title">{set.name}</p>
                    </div>
                    <div className="stat-row-figures">
                      <p className="stat-row-value">
                        {formatWeight(set.weight)} kg × {set.reps}
                      </p>
                      {set.e1rm > 0 && (
                        <p className="stat-row-note">
                          ≈{formatWeight(set.e1rm)} kg 1RM
                        </p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </details>
      )}

      <button
        type="button"
        className="ai-summary-regenerate"
        disabled={regenerating}
        onClick={onRegenerate}
      >
        {regenerating ? 'Analyzing…' : 'Regenerate'}
      </button>
    </>
  )
}

/** Total volume this window vs the previous equal one, with the change. */
function VolumeVsPrevious({
  current,
  previous,
}: {
  current: number
  previous: number
}) {
  const delta = Math.round(current - previous)
  const pct =
    previous > 0 ? Math.round(((current - previous) / previous) * 100) : null
  return (
    <div className="ai-volume">
      <div className="ai-volume-cell">
        <p className="label">This period</p>
        <p className="ai-volume-value">{formatVolume(current)}</p>
      </div>
      <div className="ai-volume-cell">
        <p className="label">Previous</p>
        <p className="ai-volume-value">{formatVolume(previous)}</p>
      </div>
      <div className="ai-volume-cell">
        <p className="label">Change</p>
        <p className={`ai-volume-value ${deltaClass(delta)}`}>
          {signedVolume(delta)}
          {pct === null ? '' : ` (${pct >= 0 ? '+' : ''}${pct}%)`}
        </p>
      </div>
    </div>
  )
}

/** Volume across the window, bucketed by day / week / month. */
function VolumeTrendChart({ trend }: { trend: TrendBucket[] }) {
  const max = Math.max(...trend.map((point) => point.volume), 1)
  return (
    <div className="ai-trend">
      <p className="label">Volume over time</p>
      <div className="ai-trend-bars">
        {trend.map((point, index) => {
          const height = Math.max(4, Math.round((point.volume / max) * 100))
          return (
            <div className="ai-trend-bar" key={`${point.label}-${index}`}>
              <span className="ai-trend-amount">
                {Math.round(point.volume).toLocaleString()}
              </span>
              <span
                className="ai-trend-fill"
                style={{ height: `${height}%` }}
              />
              <span className="ai-trend-date">{point.label}</span>
            </div>
          )
        })}
      </div>
    </div>
  )
}

/** Working-set volume by muscle group, as proportional bars. */
function MuscleGroupChart({ groups }: { groups: MuscleGroupVolume[] }) {
  const max = Math.max(...groups.map((group) => group.volume), 1)
  return (
    <div className="ai-muscles">
      <p className="label">Volume by muscle group</p>
      <ul className="ai-muscle-list">
        {groups.map((group) => (
          <li className="ai-muscle-row" key={group.name}>
            <span className="ai-muscle-name">{group.name}</span>
            <span className="ai-muscle-track">
              <span
                className="ai-muscle-fill"
                style={{ width: `${Math.max(4, (group.volume / max) * 100)}%` }}
              />
            </span>
            <span className="ai-muscle-value">
              {formatVolume(group.volume)}
            </span>
          </li>
        ))}
      </ul>
    </div>
  )
}

/** Top exercises by volume, with their estimated-1RM movement over the window. */
function TopExerciseTable({ exercises }: { exercises: ExerciseProgress[] }) {
  return (
    <div className="ai-exercises">
      <p className="label">Top exercises by volume</p>
      <table className="ai-exercise-table">
        <thead>
          <tr>
            <th>Exercise</th>
            <th>Volume</th>
            <th>Sets</th>
            <th>1RM Δ</th>
          </tr>
        </thead>
        <tbody>
          {exercises.map((exercise) => (
            <tr key={exercise.name}>
              <td className="ai-exercise-name">{exercise.name}</td>
              <td>{Math.round(exercise.volume).toLocaleString()}</td>
              <td>{exercise.sets}</td>
              <td className={deltaClass(exercise.e1rmChange)}>
                {exercise.e1rmChange === 0
                  ? '—'
                  : `${exercise.e1rmChange > 0 ? '+' : ''}${formatWeight(
                      exercise.e1rmChange,
                    )}`}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

/** A titled row of small chips — highlights or weak spots. */
function SummaryChips({
  heading,
  items,
  tone,
}: {
  heading: string
  items: string[]
  tone: 'up' | 'down'
}) {
  return (
    <div className="ai-chips">
      <p className="label">{heading}</p>
      <div className="ai-chip-row">
        {items.map((item, index) => (
          <span className={`ai-chip ai-chip-${tone}`} key={index}>
            {item}
          </span>
        ))}
      </div>
    </div>
  )
}

/**
 * The Stats tab. Every figure here is computed by Postgres and read from
 * `/api/stats/overview` — the component formats numbers and does not derive
 * them.
 *
 * Only finished workouts count, so a user who has started workouts but never
 * completed one sees the empty state rather than a screen of zeros pretending
 * to be a summary.
 */
export default function StatsPanel() {
  const stats = useStatsOverview()

  if (stats.status === 'loading') return <p className="subtitle">Loading…</p>
  if (stats.status === 'error') {
    return (
      <p className="error" role="alert">
        {stats.message}
      </p>
    )
  }
  if (stats.status === 'not-found') return null

  const { week, consistency, bodyWeight, personalRecords, recentWorkouts } =
    stats.data

  // No completed workout has ever been recorded: every section below would be a
  // zero, which reads as "you trained nothing" rather than "nothing yet".
  if (recentWorkouts.length === 0) {
    return (
      <div className="card stats-empty">
        <p className="label">No stats yet</p>
        <p className="message">Finish a workout to see your stats here.</p>
      </div>
    )
  }

  return (
    <div className="stats">
      <ProgressAiSummary />

      <section className="stats-section" aria-labelledby="stats-week-heading">
        <h3 id="stats-week-heading">This week</h3>
        <div className="stat-grid">
          <Stat label="Workouts" value={String(week.workouts)} />
          <Stat label="Training time" value={formatTrainingTime(week.seconds)} />
          <Stat label="Sets" value={String(week.sets)} />
          <Stat label="Volume" value={formatVolume(week.volumeKg)} />
        </div>
      </section>

      <section
        className="stats-section"
        aria-labelledby="stats-consistency-heading"
      >
        <h3 id="stats-consistency-heading">Consistency</h3>
        <div className="stat-grid">
          <Stat
            label="Day streak"
            value={
              consistency.currentStreakDays === 1
                ? '1 day'
                : `${consistency.currentStreakDays} days`
            }
          />
          <Stat
            label="This month"
            value={String(consistency.workoutsThisMonth)}
          />
          <Stat
            label="Avg / week"
            value={`${consistency.averageWorkoutsPerWeek}`}
          />
        </div>
      </section>

      <section className="stats-section" aria-labelledby="stats-weight-heading">
        <h3 id="stats-weight-heading">Body weight</h3>
        {bodyWeight === null ? (
          <div className="card stats-empty">
            <p className="message">
              No body weight recorded yet. Add one when you finish a workout.
            </p>
          </div>
        ) : (
          <div className="card stats-weight">
            <div>
              <p className="label">Latest</p>
              <p className="stat-value">
                {formatWeight(bodyWeight.latestKg)} kg
              </p>
              <p className="stat-row-note">
                {formatRelativeDay(bodyWeight.recordedAt)}
              </p>
            </div>
            <div className="stats-weight-change">
              <p className="label">30 days</p>
              {/* Both fields are set together by the API; narrowing both is what
                  proves it to the type checker, rather than asserting it. */}
              {bodyWeight.changeKg !== null && bodyWeight.changeSince !== null ? (
                <>
                  <Trend changeKg={bodyWeight.changeKg} />
                  <p className="stat-row-note">
                    since {formatShortDate(bodyWeight.changeSince)}
                  </p>
                </>
              ) : (
                <p className="stat-row-note">Not enough data</p>
              )}
            </div>
          </div>
        )}
      </section>

      <section className="stats-section" aria-labelledby="stats-pr-heading">
        <h3 id="stats-pr-heading">Personal records</h3>
        {personalRecords.length === 0 ? (
          <p className="subtitle">No sets logged yet.</p>
        ) : (
          <ul className="stat-list">
            {personalRecords.map((record) => (
              <PersonalRecordRow key={record.exerciseName} record={record} />
            ))}
          </ul>
        )}
      </section>

      <section className="stats-section" aria-labelledby="stats-recent-heading">
        <h3 id="stats-recent-heading">Recent workouts</h3>
        <ul className="stat-list">
          {recentWorkouts.map((workout) => (
            <RecentWorkoutRow key={workout.id} workout={workout} />
          ))}
        </ul>
      </section>
    </div>
  )
}
